_target_: models.mae.MAEEncoder
# model_name: "/homes/jpecchini/pretrained_models/vit-mae-base"
cache_dir: null
local_files_only: false
# normalize_input: true


# model_name: facebook/vit-mae-base
# cache_dir: /homes/jpecchini/.cache/huggingface